# Base Python légère
FROM python:3.12-slim

# Mettre à jour et installer gcc et libpq-dev pour psycopg2
RUN apt-get update && apt-get install -y gcc libpq-dev && rm -rf /var/lib/apt/lists/*

# Dossier de travail
WORKDIR /app

# Copier uniquement ce qu’il faut pour limiter la taille
COPY locust_consumer.py .
COPY consumer-requierment.txt .

# Installer les dépendances
RUN pip install --no-cache-dir -r consumer-requierment.txt

# Lancer le consumer
CMD ["python", "locust_consumer.py"]
