services:
  mqtt-producer: # produit vers le broker
    build:
      context: .
      dockerfile: Dockerfile-producer  
    depends_on:
      - mosquitto
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - "8089:8089" 

  mqtt-consumer: # consomme le broker
    build:
      context: .
      dockerfile: Dockerfile-consumer  
    depends_on:
      - mosquitto
      - timescaledb
    environment:
      - PYTHONUNBUFFERED=1

  api: # pour le rendu final
    build:
      context: ./api
      dockerfile: Dockerfile-api
    depends_on:
      - timescaledb
    environment:
      - PYTHONUNBUFFERED=1
      - DB_HOST=timescaledb
      - DB_PORT=5432
      - DB_NAME=tsdb
      - DB_USER=tsuser
      - DB_PASS=tspassword
    ports: 
      - 8000:8000


  mosquitto: # broker
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log

  timescaledb: # postgres ext db
      image: timescale/timescaledb:latest-pg16
      container_name: timescaledb
      environment:
        POSTGRES_USER: tsuser
        POSTGRES_PASSWORD: tspassword
        POSTGRES_DB: tsdb
      ports:
        - "5432:5432"
      volumes:
        - ./timescaledb/data:/var/lib/postgresql/data


  pgadmin: # ui db
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80" 
    depends_on:
      - timescaledb
    volumes:
      - pgadmin_data:/var/lib/pgadmin


  grafana:
    image: grafana/grafana:12.3.0-17782621999
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - timescaledb
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana


  # angular:
  #   build:
  #     context: ./bot-ui
  #     dockerfile: Dockerfile
  #   ports:
  #     - "4200:4200"
  #   volumes:
  #     - ./bot-ui:/app


  # mqtt-explorer: autre UI
  #   image: smeagolworms4/mqtt-explorer
  #   container_name: mqtt-explorer
  #   ports:
  #     - "4000:4000"   # UI web MQTT Explorer
  #   depends_on:
  #     - mosquitto

volumes:
  grafana_data:
  pgadmin_data: